version: "3"

services:
    sfa_get_sodata:
        build: sfa_get_sodata
        image: sfa_get_sodata
        restart: always
        #restart: "no"
        environment:
            TZ: ${TZ}
            USERNAME: ${USERNAME}
            CLIENTID: ${CLIENTID}
            JWTKEYFILE: ${JWTKEYFILE}
        logging:
            driver: ${LOGDRIVER}
    mongo:
        image: mongodb_custom
        build: mongodb_custom
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: "sObjectData"
        #logging:
        #    driver: ${LOGDRIVER}
        #volumes:
        #    - ./mongodb_data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: ${MONGO_OPTIONS_EDITORTHEME}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
        logging:
            driver: ${LOGDRIVER}

    flask_sfadata_replicaapi:
        image: flask_sfadata_replicaapi
        build: flask_sfadata_replicaapi
        restart: always
        volumes:
            - ./flask_sfadata_replicaapi/code:/code
        ports:
            - "5000:5000"
        environment:
            TZ: Asia/Tokyo
            PYTHONDONTWRITEBYTECODE: 1
            FLASK_DEBUG: "True"
            FLASK_ENV: development
