version: "3"
services:
    sfadata_replica:
        build: sfadata_replica
        image: sfadata_replica
        restart: always
        #restart: "no"
        environment:
            TZ: ${TZ}
            USERNAME: ${USERNAME}
            CLIENTID: ${CLIENTID}
            JWTKEYFILE: ${JWTKEYFILE}
        logging:
            driver: ${LOGDRIVER}
        volumes:
            - ./uploadvolume:/uploadvolume
    mongo:
        image: mongodb_custom
        build: mongodb_custom
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: "sObjectData"
        #logging:
        #    driver: ${LOGDRIVER}
        #volumes:
        #    - ./mongodb_data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: ${MONGO_OPTIONS_EDITORTHEME}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
        logging:
            driver: ${LOGDRIVER}

    accessormongo:
        image: accessormongo
        build: accessormongo
        restart: always
        volumes:
            - ./accessormongo/code:/code
        ports:
            - "35000:5000"
        environment:
            TZ: Asia/Tokyo
            PYTHONDONTWRITEBYTECODE: 1
            FLASK_DEBUG: "True"
            FLASK_ENV: development

    boxuploader:
        image: boxuploader
        build: boxuploader
        ports:
            - "35001:5000"
        # restart: always
        restart: "no"
        environment:
            TZ: ${TZ}
            BOX_USER_ID: ${BOX_USER_ID}
            BOX_UPLOADFOLDER_ID: ${BOX_UPLOADFOLDER_ID}
            BOX_PIPELINEDATA_ID: ${BOX_PIPELINEDATA_ID}
            BOX_QUERYALLDATA_ID: ${BOX_QUERYALLDATA_ID}
            PYTHONDONTWRITEBYTECODE: 1
            FLASK_DEBUG: "True"
            FLASK_ENV: development
        volumes:
            - ./boxuploader/code:/code
            - ./uploadvolume:/uploadvolume
#volumes:
#    uploadvolume:
