# FROM node:latest
FROM node:14-alpine AS builder
LABEL maintaner='y-yoshimoto'
ENV APPNAME SalesforceAdminDashboard

RUN mkdir -p /$APPNAME/src && mkdir -p /$APPNAME/public
WORKDIR /$APPNAME

COPY ./package.json /$APPNAME/package.json

RUN yarn install
COPY ./src /$APPNAME/src
COPY ./public /$APPNAME/public

RUN yarn build

# React App set Nginx
FROM nginx
LABEL  maintainer "y.yoshimoto"
ENV APPNAME SalesforceAdminDashboard
# コンテツファイルの設置
COPY --from=builder /$APPNAME/build/ /usr/share/nginx/html/

# nginx設定ファイルの設置
COPY nginx.conf /etc/nginx/nginx.conf
COPY server.conf /etc/nginx/conf.d/server.conf

# コンテナ実行時の動作設定
EXPOSE 80 443
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
